import { NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>next-app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <h1>About</h1>
    </>
  );
};

export default About;
